# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YugiohCollectionView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for YugiohCollectionView
 pod "Alamofire"
 pod "SDWebImage"
 pod "Cosmos"
 pod "NVActivityIndicatorView"

end
